SPOTIPY_CLIENT_ID = "e419e60b293c4c13b7c67ab86780c2ef"
SPOTIPY_CLIENT_SECRET = "aff4838b31af4d36965b1d84c40d24da"
SPOTIPY_REDIRECT_URI = "http://localhost:8888/callback"
PLAYLIST_ID = "3sWEAhblnH7czKePUu9ljb"